# Generated by Django 3.1.7 on 2021-03-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postIn',
            new_name='comment_to',
        ),
    ]
